name: Build Executable MacOs

on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Step 1 - Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Step 2 - Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
      - name: Step 3 - Build executable for MacOs
        run: |
          pyinstaller --onefile --add-data 'templates:templates' --add-data 'static:static' app.py
      - name: Step 4 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: builded
          path: dist/*
